org: nidhoggspec
app: serverlesszoluxiones
service: RetoTecnicoZoluxiones
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:*
      Resource: 
        - arn:aws:dynamodb:us-west-2:809740043145:table/starWars
functions:
  LambdaGET:
    handler: src/controllers/getRequest
    name: ${sls:stage}--getCharacters
    events:
      - httpApi:
          path: '/people'
          method: get
